# ?????????? ?????? ?????? Log4j (?????? ????????????)
status = warn
name = CalculatorConfig

# ????????? ??????? ? ?????????
filters = threshold
filter.threshold.type = ThresholdFilter
filter.threshold.level = debug

# ????????? ?????? ? ???????
appender.console.type = Console
appender.console.name = LogToConsole
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} [%p] %c{1} - %m%n

# ????????? ???????? ??????? (Root)
rootLogger.level = debug
rootLogger.appenderRef.stdout.ref = LogToConsole